CREATE TABLE IF NOT EXISTS event (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    seats INTEGER NOT NULL,
    book_second_max_time INTEGER NOT NULL DEFAULT 60*5
);

CREATE TABLE IF NOT EXISTS book(
  id BIGSERIAL PRIMARY key,
  event_id BIGINT REFERENCES event(id) ON DELETE CASCADE,
  status INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);


