CREATE TABLE IF NOT EXISTS orders (
  order_uid uuid PRIMARY KEY,
  track_number TEXT NOT NULL,
  entry TEXT NOT NULL,
  locale TEXT NOT NULL,
  internal_signature TEXT,
  customer_id TEXT NOT NULL,
  delivery_service TEXT NOT NULL,
  shard_key VARCHAR(4) NOT NULL,
  sm_id INTEGER NOT NULL,
  date_created TIMESTAMPTZ NOT NULL,
  oof_shard VARCHAR(4) NOT NULL
);

CREATE TABLE IF NOT EXISTS deliveries (
  ORDER_UID UUID PRIMARY KEY REFERENCES ORDERS(ORDER_UID) ON DELETE CASCADE,
  NAME TEXT NOT NULL,
  PHONE VARCHAR(11) NOT NULL,
  ZIP VARCHAR(7) NOT NULL,
  CITY TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  REGION TEXT NOT NULL,
  EMAIL TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS payments (
  transaction UUID PRIMARY KEY REFERENCES ORDERS(ORDER_UID) ON DELETE CASCADE,
  request_id TEXT,
  currency VARCHAR(10) NOT NULL,
  provider TEXT NOT NULL,
  amount INTEGER NOT NULL,
  payment_dt BIGINT NOT NULL,
  bank TEXT NOT NULL,
  delivery_cost INTEGER NOT NULL,
  goods_total INTEGER NOT NULL,
  custom_fee INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS items (
  order_uid uuid REFERENCES ORDERS(ORDER_UID) ON DELETE CASCADE,
  chrt_id INTEGER NOT NULL,
  track_number VARCHAR NOT NULL,
  price INTEGER NOT NULL,
  rid VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  sale INTEGER NOT NULL,
  size VARCHAR NOT NULL,
  total_price INTEGER NOT NULL,
  nm_id INTEGER NOT NULL,
  brand VARCHAR NOT NULL,
  status INTEGER NOT NULL
);
